version: 2
jobs:
  checkout_code: 
    docker:
      - image: google/cloud-sdk
    working_directory: ~/GIT/zumo/webapps/aptool/aptool
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: 
            - .

  build:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/GIT/zumo/webapps/aptool/aptool
    steps:
      - checkout
      - run:
          name: Install  dependencies
          command: 'npm install'
      
  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/GIT/zumo/webapps/aptool/aptool
    steps: 
      - run:
          name: Production Deployment 
          command: |
              echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
              gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
              gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
  
  run_db_migrations: 
    docker:
       - image: google/cloud-sdk
    working_directory: ~/GIT/zumo/webapps/aptool/aptool
    steps:
      - run:
          name: Run Database Migrations
          command: npx sequelize-cli db:migrate
    
workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
  deploy:
    jobs:
      - checkout_code
      - build:
          requires: 
            - checkout_code
      - run_db_migrations:
          requires:
            - checkout_code
            - build
      - deploy:
          requires:
            - checkout_code
            - build
            - run_db_migrations
          filters:
            branches:
              only:
                 - master
        