version: 2
orbs:
  heroku: circleci/heroku@1.0.0
jobs:
  checkout_code: 
    docker:
      - image: circleci/node:10
    working_directory: ~/GIT/zumo/webapps/aptool/aptool
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: 
            - .

  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/GIT/zumo/webapps/aptool/aptool
    steps:
      - checkout
      - run:
          name: Install  dependencies
          command: 'npm install'
      
  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/GIT/zumo/webapps/aptool/aptool
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to production 
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master



workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
  deploy:
    jobs:
      - checkout_code
      - build:
          requires: 
            - checkout_code
      - deploy:
          requires:
            - checkout_code
            - build
          filters:
            branches:
              only:
                 - master
        