version: 2
orbs:
  heroku: circleci/heroku@1.0.0
jobs:
  checkout_code: 
    docker:
      - image: circleci/node:10
    working_directory: ~/GIT/zumo/webapps/aptool/aptool
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: 
            - .

  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/GIT/zumo/webapps/aptool/aptool
    steps:
      - checkout
      - run:
          name: Install  dependencies
          command: 'npm install'
      
  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/GIT/zumo/webapps/aptool/aptool
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Production Deployment 
          command:  |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}


workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
  deploy:
    jobs:
      - checkout_code
      - build:
          requires: 
            - checkout_code
      - deploy:
          requires:
            - checkout_code
            - build
          filters:
            branches:
              only:
                 - master
        